# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190714_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='vm_status',
            field=models.IntegerField(choices=[(0, '在线'), (1, '下线')], verbose_name='服务器状态'),
        ),
    ]
