# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20190714_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='hostname',
            field=models.CharField(max_length=100, unique=True, verbose_name='主机名'),
        ),
    ]
