# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190707_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users51reboot',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
