# Generated by Django 2.2 on 2019-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_workorder_handle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='handle_time',
            field=models.DateTimeField(auto_now=True, verbose_name='处理时间'),
        ),
    ]
