# Generated by Django 2.2 on 2019-08-19 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_auto_20190819_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='handle_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='处理时间'),
            preserve_default=False,
        ),
    ]
