# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190707_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'users', 'verbose_name_plural': 'users'},
        ),
    ]
