# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190707_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['username'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
