# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190714_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='Beijing', max_length=100),
            preserve_default=False,
        ),
    ]
