# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='车')),
            ],
            options={
                'verbose_name': '车',
                'verbose_name_plural': '车',
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='制造商')),
            ],
            options={
                'verbose_name': '制造商',
                'verbose_name_plural': '制造商',
                'db_table': 'manufacturer',
            },
        ),
    ]
