# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_car_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Manufacturer'),
            preserve_default=False,
        ),
    ]
