# Generated by Django 2.2 on 2019-08-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20190826_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='build_serial',
            field=models.IntegerField(default=0, max_length=40, null=True, verbose_name='构建序号'),
        ),
    ]
