# Generated by Django 2.2 on 2019-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_deploy_build_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='build_url',
            field=models.CharField(max_length=100, null=True, verbose_name='构建链接'),
        ),
    ]
