# Generated by Django 2.2.4 on 2019-08-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_auto_20190824_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder_contents',
            options={'ordering': ['-replay_time'], 'verbose_name': 'worlorder_contents', 'verbose_name_plural': 'worlorder_contents'},
        ),
        migrations.AddField(
            model_name='workorder_contents',
            name='write_user',
            field=models.CharField(default='', max_length=32, verbose_name='写入用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorder_contents',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contents', to='work_order.WorkOrder', verbose_name='工单id'),
        ),
    ]
