# Generated by Django 2.2.4 on 2019-08-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='order_contents',
        ),
        migrations.CreateModel(
            name='WorkOrder_Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_contents', models.TextField(verbose_name='工单内容')),
                ('replay_time', models.DateTimeField(auto_now=True, verbose_name='处理完成时间')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.WorkOrder', verbose_name='工单id')),
            ],
        ),
    ]
