# Generated by Django 2.2.4 on 2019-08-24 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_auto_20190824_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=16, verbose_name='用于WorkOrder_Contents取id'),
            preserve_default=False,
        ),
    ]
