# Generated by Django 2.2.4 on 2019-08-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_workorder_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='tag',
            field=models.CharField(max_length=18, verbose_name='用于WorkOrder_Contents取id'),
        ),
    ]
